version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/brain_agriculture
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run build && npm run migration:run && npm run start:dev"
    networks:
      - api_network

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brain_agriculture
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api_network

volumes:
  postgres_data:

networks:
  api_network:
    driver: bridge
    name: api_network